import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./providers";
import NavMenu from "@/components/core/navMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Template app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <main className="flex min-h-screen max-w-screen flex-col items-center">
            <NavMenu />
            {children}
          </main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
