"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./providers";
import NavMenu from "@/components/core/navMenu";
import Link from "next/link";
import React, { Suspense } from "react";
import { AiProvider } from "@/context/AiProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//    title: "Template app",
//    description: "Generated by create next app",
// };

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <NextAuthProvider>
               <main className="flex min-h-screen max-w-screen flex-col items-center">
                  <NavMenu />
                  <Suspense fallback={<div>Suspense from layout...</div>}>
                     <AiProvider>{children}</AiProvider>
                  </Suspense>
               </main>
            </NextAuthProvider>
            <footer>
               <Link href={"https://github.com/Isendoum"}>
                  Find more information on github repo
               </Link>
            </footer>
         </body>
      </html>
   );
}
