#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

# Detect OS and set appropriate npm command
OS="$(uname -s)"
case "$OS" in
  Linux*|Darwin*)
    npm_command="npm"
    ;;
  MINGW*|MSYS*|CYGWIN*)
    OS='Windows'
    npm_command="npm.cmd"
    ;;
  *)
    echo "Unknown operating system: $OS"
    exit 1
    ;;
esac

# Execute commands based on the operating system
if [ "$OS" = "Windows" ]; then
    # Windows-specific commands
    "$npm_command" run format:staged
else
    # Unix/Linux/Mac commands
    npm run format:staged
fi
